sudo: required
services:
  - docker

before_install:
  - docker build -t mehtav23/docker-react -f Dockerfile.dev .

script:
  - docker run -2 CI=true mehtav23/docker-react npm run test -- --coverage

language: generic